"""``deployctl ci`` — CI/CD: the workflows, GitHub's secrets, and deploying through it.

Every manual step of setting up continuous deployment is a command here, in the
order a project goes through them:

    ci connect      gh logged in, which repository, which plan → CI_SCOPE
    ci init         .github/workflows: build-image.yml, deploy.yml (+ ci.yml once)
    ci setup-key    a CI-only ssh key on every host, its private half in GitHub
    ci pin-hosts    the hosts' keys from this machine's known_hosts, into GitHub
    ci sync-config  this machine's config/ into GitHub, as one secret
    ci doctor       all of the above, checked
    ci deploy       run the deploy workflow (a tag, a config change, a rollback)
    ci runs         what the workflow deployed, and how it went
    ci auto-deploy  merges to the deploy branch deploy themselves, or not
"""

from __future__ import annotations

import datetime
import difflib
import json
import os
import re
import subprocess
import sys
import tempfile
import time

import jinja2
import typer

from ... import __version__
from .. import bundle, github, paths, secrets, tags, ui
from ..config import Config
from ..context import env_option, load_config, resolve_env
from ..envfile import parse_env_text, patch_env_file, read_env_file
from ..runner import run
from .deploy import parse_history, previous_release

ci_app = typer.Typer(
    name="ci",
    help="CI/CD: generate the workflows, connect GitHub, and deploy through it.",
    no_args_is_help=True,
)

#: Where the deploy workflow installs deployctl from — pinned to this version.
TOOL_REPO = "hybridinteract/deployctl"

#: Third-party actions, pinned to commit SHAs: the deploy job holds the production
#: ssh key. Bumping one is a change here, then `ci init --force` in each project.
ACTIONS = {
    "checkout": "3d3c42e5aac5ba805825da76410c181273ba90b1", "checkout_version": "v7.0.1",
    "setup_uv": "c18668ad3cf93ea998bef934396af7bb5c839dc7", "setup_uv_version": "v10.2.0",
    "login": "dbcb813823bdd20940b903addbd779551569679f", "login_version": "v4.6.0",
    "buildx": "f87e5991a6d7451dcb8d9637bfbc97413f497069", "buildx_version": "v4.4.1",
    "build_push": "c3c9e263c25d99ce0380d002d59b67737d91b0dc", "build_push_version": "v7.4.0",
    "tailscale": "d1b6cd204f8dceda5b3eaad7f1f767be390056cd", "tailscale_version": "v4.2.0",
}

#: Regenerated by `ci init` — edits are overwritten, so they carry a header saying so.
MANAGED = ("build-image.yml", "deploy.yml")
#: Written once and then the project's own: its checks are its business.
OWNED = "ci.yml"
_MANAGED_HEADER = re.compile(r"^# Managed by deployctl (\S+)")

_repo_level_option = typer.Option(
    False,
    "--repo-level",
    help="Store at repository level this once. CI_SCOPE=repository (set by `ci connect` on "
    "GitHub Free) does it every time.",
)


# ---- shared ------------------------------------------------------------------------


def _github() -> None:
    try:
        github.require()
    except github.GitHubError as exc:
        ui.error(str(exc))
        raise typer.Exit(2) from None


def scope_env(cfg: Config, repo_level: bool = False) -> str | None:
    """The GitHub environment the secrets live on, or None for the repository."""
    if repo_level or cfg.raw["CI_SCOPE"] == "repository":
        return None
    return cfg.env


def _where(cfg: Config, scope: str | None) -> str:
    return f"GitHub environment '{scope}'" if scope else "the repository's Actions secrets"


def workflows_dir():
    return paths.REPO_ROOT / ".github" / "workflows"


def deploy_timeout(hosts: int) -> int:
    """Minutes for the deploy job: a few per host, so a fleet is never cut off mid-roll."""
    return max(20, min(360, 10 + 4 * max(1, hosts)))


def _render(name: str, ctx: dict) -> str:
    """Render a workflow with «…» delimiters.

    A GitHub Actions file is full of ``${{ … }}`` that must reach GitHub verbatim;
    moving Jinja's variable delimiters beats wrapping half the file in raw blocks.
    Statements keep ``{% … %}``, which GitHub never uses.
    """
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(paths.TEMPLATES_DIR / "ci")),
        undefined=jinja2.StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
        variable_start_string="«",
        variable_end_string="»",
        autoescape=False,
    )
    return env.get_template(f"{name}.j2").render(**ctx)


def _context(cfg: Config) -> dict:
    return {
        "VERSION": __version__,
        "TOOL_REPO": TOOL_REPO,
        "TOOL_REF": f"v{__version__}",
        "ENV": cfg.env,
        "DEPLOY_BRANCH": cfg.raw["DEPLOY_BRANCH"],
        "IMAGE_REPO": cfg.raw["IMAGE_REPO"],
        "REGISTRY_HOST": cfg.derived["REGISTRY_HOST"] or "ghcr.io",
        "CI_BUILD_CONTEXT": cfg.derived["CI_BUILD_CONTEXT"],
        "CI_DOCKERFILE": cfg.derived["CI_DOCKERFILE"],
        "BUILD_TARGET": cfg.raw["BUILD_TARGET"],
        "WORKER_BUILD_TARGET": cfg.raw["WORKER_BUILD_TARGET"],
        "IMAGE_PLATFORM": cfg.raw["IMAGE_PLATFORM"],
        "HOST_COUNT": len(cfg.hosts),
        "TIMEOUT_MINUTES": deploy_timeout(len(cfg.hosts)),
        "ACTIONS": ACTIONS,
    }


def _jump_target(jump: str) -> tuple[str, str]:
    """The first hop of SSH_JUMP_HOST as ``(host, port)``, user dropped."""
    first = jump.split(",", 1)[0].split("@")[-1]
    host, _, port = first.partition(":")
    return host, port


# ---- ci connect ----------------------------------------------------------------------


@ci_app.command("connect")
def connect(
    env: str = env_option(),
    branch: str = typer.Option(None, "--branch", "-b", help="The deploy branch, saved as DEPLOY_BRANCH."),
) -> None:
    """Check gh, find the repository and its plan, and record where secrets go (CI_SCOPE).

    A private repository on GitHub Free has no environment secrets, so they go on
    the repository. Anything else gets them on the GitHub environment, readable
    only from the branches its rules allow.
    """
    env_name = resolve_env(env)
    _github()
    try:
        info = github.repo()
    except github.GitHubError as exc:
        ui.error(str(exc))
        ui.hint("run this inside the application's git repository, with a GitHub remote")
        raise typer.Exit(2) from None
    plan = github.plan(info["owner"])

    if not info["private"]:
        scope, why = "environment", "a public repository has environment secrets on every plan"
    elif plan and plan != "free":
        scope, why = "environment", f"GitHub {plan} gives a private repository environment secrets"
    elif plan == "free":
        scope, why = "repository", "GitHub Free has no environment secrets for a private repository"
    else:
        scope, why = "repository", "this account cannot see the plan; repository secrets work on every plan"

    values = {"CI_SCOPE": scope}
    if branch:
        values["DEPLOY_BRANCH"] = branch
    patch_env_file(paths.COMMON_CONFIG, values)
    cfg = load_config(env_name, require_valid=False)

    ui.header("CI connect")
    ui.kv("repository", f"{info['name']}  ({'private' if info['private'] else 'public'})")
    ui.kv("plan", plan or "not visible to this account")
    ui.kv("secrets", f"{scope} — {why}")
    ui.kv("deploy branch", cfg.raw["DEPLOY_BRANCH"])
    ui.ok(f"saved CI_SCOPE={scope} in config/common.env")
    if scope == "repository" and info["private"]:
        ui.warn("repository secrets are readable from ANY branch by anyone with write access — including "
                "the ssh key, which is root on the hosts. GitHub Team scopes them to the deploy branch.")
    print()
    ui.info(f"Next: deployctl ci init --env {env_name}")


# ---- ci init -------------------------------------------------------------------------


@ci_app.command("init")
def init(
    env: str = env_option(),
    branch: str = typer.Option(
        None, "--branch", "-b", help="The deploy branch, saved as DEPLOY_BRANCH. Default: DEPLOY_BRANCH (main)."
    ),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite workflows that differ from the templates."),
) -> None:
    """Write .github/workflows/build-image.yml and deploy.yml, and ci.yml if there is none.

    build-image.yml and deploy.yml are managed: regenerated from this version's
    templates, and a file that differs is shown as a diff and needs --force.
    ci.yml is written once and is then the project's own — its checks.
    """
    cfg = load_config(env, require_valid=False)
    if not cfg.raw["IMAGE_REPO"] or "your-org" in cfg.raw["IMAGE_REPO"]:
        ui.error("IMAGE_REPO is not set — fill it in config/common.env first")
        raise typer.Exit(1)
    if branch:
        patch_env_file(paths.COMMON_CONFIG, {"DEPLOY_BRANCH": branch})
        cfg.raw["DEPLOY_BRANCH"] = branch

    ctx = _context(cfg)
    target = workflows_dir()
    target.mkdir(parents=True, exist_ok=True)
    blocked = []
    for name in MANAGED:
        path = target / name
        rel = path.relative_to(paths.REPO_ROOT)
        content = _render(name, ctx)
        if path.is_file():
            current = path.read_text()
            if current == content:
                ui.info(f"{rel} is current")
                continue
            if not force:
                blocked.append(str(rel))
                diff = list(difflib.unified_diff(current.splitlines(), content.splitlines(),
                                                 f"{rel} (now)", f"{rel} (deployctl {__version__})", lineterm="", n=1))
                ui.warn(f"{rel} differs from the template ({sum(l.startswith('+') for l in diff[2:])} added, "
                        f"{sum(l.startswith('-') for l in diff[2:])} removed lines):")
                for line in diff[:40]:
                    print(f"    {line}")
                if len(diff) > 40:
                    print(f"    … {len(diff) - 40} more lines")
                continue
        path.write_text(content)
        ui.ok(f"wrote {rel}")

    owned = target / OWNED
    rel_owned = owned.relative_to(paths.REPO_ROOT)
    if not owned.is_file():
        owned.write_text(_render(OWNED, ctx))
        ui.ok(f"wrote {rel_owned} — yours from now on: put your checks in its `checks` job")
    else:
        text = owned.read_text()
        if "build-image.yml" not in text or "deploy.yml" not in text:
            ui.warn(f"{rel_owned} is your own and was left alone — but it does not call "
                    f"{'build-image.yml' if 'build-image.yml' not in text else 'deploy.yml'}.")
            ui.hint("add these two jobs to it, after your checks (and list your checks in `needs`):")
            skeleton = _render(OWNED, ctx)
            print(skeleton[skeleton.index("  publish:"):])

    if blocked:
        ui.error(f"not overwritten: {', '.join(blocked)} — review the diff above, then: deployctl ci init --force")
        raise typer.Exit(1)
    print()
    ui.info("Next, once: Settings → Actions → General → Workflow permissions → \"Read and write\" (image push)")
    ui.info(f"then: deployctl ci setup-key --env {cfg.env} && deployctl ci pin-hosts --env {cfg.env} "
            f"&& deployctl ci sync-config --env {cfg.env}")


# ---- ci setup-key --------------------------------------------------------------------


def _ci_key(cfg: Config, mode: str, **extra: str) -> list[tuple[str, str]]:
    """``deploy.sh ci-key`` → ``[(verdict, where), …]``."""
    proc = run(cfg, "deploy.sh", ["ci-key"], check=False, capture=True,
               extra_env={"CI_KEY_MODE": mode, **extra})
    results = []
    for line in proc.stdout.splitlines():
        verdict, _, where = line.partition(" ")
        if verdict in ("PRESENT", "ABSENT", "INSTALLED", "OK", "FAILED", "UNREACHABLE"):
            results.append((verdict, where))
    if not results and proc.returncode != 0:
        ui.error((proc.stderr or proc.stdout).strip() or "deploy.sh ci-key failed")
        raise typer.Exit(1)
    return results


@ci_app.command("setup-key")
def setup_key(
    env: str = env_option(),
    rotate: bool = typer.Option(False, "--rotate", help="Replace the CI key already installed."),
    repo_level: bool = _repo_level_option,
) -> None:
    """Make a CI-only ssh key, install it on every host, and hand its private half to GitHub.

    The key is generated in a private temporary directory and deleted when this
    returns: GitHub holds the only copy. Its public half goes on every host (and
    the jump host) with `restrict`, installed with your own ssh access, and it is
    proven to log in on its own before it is uploaded. Only its fingerprint is
    ever printed.
    """
    env_name = resolve_env(env)
    cfg = load_config(env_name)
    _github()
    info = github.repo()
    scope = scope_env(cfg, repo_level)
    comment = f"deployctl-ci@{info['name']}/{env_name}"

    ui.header(f"CI deploy key — {env_name}")
    with tempfile.TemporaryDirectory(prefix="deployctl-ci-key-") as tmp:
        key = os.path.join(tmp, "id_ed25519")
        subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", comment, "-f", key], check=True)
        pub = open(key + ".pub").read().strip()
        fingerprint = subprocess.run(["ssh-keygen", "-lf", key + ".pub"], capture_output=True, text=True).stdout.strip()

        now = _ci_key(cfg, "check", CI_KEY_COMMENT=comment)
        installed = [where for verdict, where in now if verdict == "PRESENT"]
        unreachable = [where for verdict, where in now if verdict == "UNREACHABLE"]
        if unreachable:
            ui.error(f"cannot reach {', '.join(unreachable)} with your own ssh access")
            raise typer.Exit(1)
        if installed and not rotate:
            ui.error(f"a CI key for {info['name']}/{env_name} is already on {', '.join(installed)}")
            ui.hint("replace it: deployctl ci setup-key --rotate  (the old one stops working everywhere)")
            raise typer.Exit(1)

        results = _ci_key(cfg, "rotate" if rotate else "install", CI_KEY_COMMENT=comment, CI_PUBKEY=pub)
        failed = [where for verdict, where in results if verdict != "INSTALLED"]
        for verdict, where in results:
            (ui.ok if verdict == "INSTALLED" else ui.error)(f"{where}: {verdict.lower()}")
        if failed:
            ui.error("not installed everywhere — nothing was uploaded; fix the above and run again with --rotate")
            raise typer.Exit(1)

        proof = _ci_key(cfg, "verify", CI_KEY_COMMENT=comment, CI_KEY_FILE=key)
        refused = [where for verdict, where in proof if verdict != "OK"]
        if refused:
            ui.error(f"the new key does not log in on its own to {', '.join(refused)} — nothing was uploaded")
            ui.hint("check the deploy user's ~/.ssh permissions there (700 for the directory, 600 for the file)")
            raise typer.Exit(1)
        ui.ok("the key logs in on its own to every host")

        try:
            with open(key) as handle:
                github.set_secret("DEPLOY_SSH_KEY", handle.read(), scope)
        except github.GitHubError as exc:
            ui.error(str(exc))
            raise typer.Exit(1) from None

    ui.ok(f"DEPLOY_SSH_KEY → {_where(cfg, scope)}; the local copy is deleted")
    ui.kv("fingerprint", fingerprint)
    ui.kv("comment", f"{comment}   (what --rotate finds on the hosts)")


# ---- ci pin-hosts --------------------------------------------------------------------


def known_hosts_lines(host: str, port: str = "") -> list[str]:
    """This machine's trusted keys for a host, as known_hosts lines (hashed or not)."""
    name = f"[{host}]:{port}" if port and port != "22" else host
    proc = subprocess.run(["ssh-keygen", "-F", name], capture_output=True, text=True)
    return [line for line in proc.stdout.splitlines() if line and not line.startswith("#")]


@ci_app.command("pin-hosts")
def pin_hosts(env: str = env_option(), repo_level: bool = _repo_level_option) -> None:
    """Give GitHub the host keys this machine already trusts (DEPLOY_KNOWN_HOSTS).

    CI refuses any host key it was not given (DEPLOYCTL_SSH_STRICT), so every host
    — and the jump host — must be here. Keys come from this machine's known_hosts,
    which learned them the first time you connected: a host you have never
    connected to is refused rather than looked up.
    """
    env_name = resolve_env(env)
    cfg = load_config(env_name)
    _github()
    scope = scope_env(cfg, repo_level)
    targets = [(host, "") for host in cfg.hosts]
    if cfg.raw["SSH_JUMP_HOST"]:
        targets.append(_jump_target(cfg.raw["SSH_JUMP_HOST"]))

    lines, missing = [], []
    for host, port in targets:
        found = known_hosts_lines(host, port)
        if found:
            lines += found
        else:
            missing.append(f"{host}:{port}" if port else host)
    if missing:
        ui.error(f"this machine has never connected to {', '.join(missing)}, so it has no key to pin")
        ui.hint("connect once, checking the fingerprint it shows against the host's console: "
                f"ssh {cfg.raw['SSH_USER']}@{missing[0]} true")
        raise typer.Exit(1)
    try:
        github.set_variable("DEPLOY_KNOWN_HOSTS", "\n".join(lines), scope)
    except github.GitHubError as exc:
        ui.error(str(exc))
        raise typer.Exit(1) from None
    ui.ok(f"DEPLOY_KNOWN_HOSTS → {_where(cfg, scope)}: {len(lines)} key(s) for {len(targets)} host(s)")


# ---- ci sync-config / status / unpack: this machine's config/ → GitHub → the runner ----


def _collect(env: str) -> dict[str, str]:
    try:
        return bundle.collect(env)
    except bundle.BundleError as exc:
        ui.error(str(exc))
        raise typer.Exit(1) from None


def _remote_digest(scope: str | None) -> tuple[str | None, str]:
    """``(digest, "")`` from GitHub, or ``(None, why not)``."""
    try:
        value = github.variables(scope).get(bundle.DIGEST_NAME)
    except github.GitHubError as exc:
        if "404" in str(exc) or "not found" in str(exc).lower():
            return None, "nothing uploaded yet" + (f" (or no GitHub environment named '{scope}')" if scope else "")
        return None, str(exc)
    return (value, "") if value else (None, "nothing uploaded yet")


@ci_app.command("sync-config")
def sync_config(
    env: str = env_option(),
    force: bool = typer.Option(False, "--force", "-f", help="Upload even when GitHub's copy already matches."),
    repo_level: bool = _repo_level_option,
) -> None:
    """Upload this environment's config/ to GitHub, for the deploy workflow.

    Run it after every config change made on this machine — in the panel or by
    hand. CI deploys with the uploaded copy, and refuses to change a value the
    hosts are running with, so a copy left stale makes the next deploy stop
    rather than quietly revert your change.
    """
    env_name = resolve_env(env)
    _github()
    # Upload only what would deploy: an invalid config would fail in CI later, and
    # a missing generated secret would fail there too (CI never mints one).
    cfg = load_config(env_name)
    scope = scope_env(cfg, repo_level)
    stored = read_env_file(paths.secrets_file(env_name))
    unminted = [k for k in secrets.pinned(cfg) if not stored.get(k) and not cfg.raw_input.get(k)]
    if unminted:
        ui.error(f"config/secrets.{env_name}.env has no {', '.join(unminted)}")
        ui.hint(f"run `deployctl setup --env {env_name}` first — CI never generates secrets")
        raise typer.Exit(1)

    files = _collect(env_name)
    local = bundle.digest(files)
    remote, _ = _remote_digest(scope)
    if remote == local and not force:
        ui.ok(f"GitHub's copy of '{env_name}' is already current ({local[:19]}…)")
        return

    # Secret first, digest second: if the second call fails, CI holds a bundle it
    # cannot verify and refuses it — failing closed rather than deploying either copy.
    try:
        github.set_secret(bundle.SECRET_NAME, bundle.encode(files), scope)
    except github.GitHubError as exc:
        ui.error(str(exc))
        if scope:
            ui.hint(f"no GitHub environment '{env_name}'? Create it, or on GitHub Free: deployctl ci connect")
        raise typer.Exit(1) from None
    try:
        github.set_variable(bundle.DIGEST_NAME, local, scope)
    except github.GitHubError as exc:
        ui.error(f"uploaded the bundle but not its digest: {exc}")
        ui.hint("CI refuses the bundle until they match — re-run this command")
        raise typer.Exit(1) from None

    ui.ok(f"uploaded config for '{env_name}' → {_where(cfg, scope)} ({local[:19]}…)")
    for name in sorted(files):
        print(f"    {name:<28} {len(parse_env_text(files[name]))} keys")


@ci_app.command("status")
def status(env: str = env_option(), repo_level: bool = _repo_level_option) -> None:
    """Is GitHub's copy of this environment's config/ the same as this machine's?

    Exit 0 when it is, 1 when it differs or was never uploaded, 2 when it cannot
    be checked.
    """
    env_name = resolve_env(env)
    _github()
    cfg = load_config(env_name, require_valid=False)
    scope = scope_env(cfg, repo_level)
    local = bundle.digest(_collect(env_name))
    remote, why = _remote_digest(scope)
    if remote is None:
        ui.warn(f"GitHub has no config for '{env_name}': {why}")
        ui.hint(f"deployctl ci sync-config --env {env_name}")
        raise typer.Exit(1 if "nothing uploaded" in why else 2)
    if remote != local:
        ui.warn(f"GitHub's copy of '{env_name}' differs from this machine's config/")
        ui.hint(f"this machine: {local[:19]}…   GitHub: {remote[:19]}…")
        ui.hint(f"if this machine has the newer config: deployctl ci sync-config --env {env_name}")
        raise typer.Exit(1)
    ui.ok(f"GitHub's copy of '{env_name}' matches this machine's config/ ({local[:19]}…)")


@ci_app.command("unpack")
def unpack(
    env: str = env_option(),
    force: bool = typer.Option(
        False, "--force", "-f", help="Replace config files that already exist with different contents."
    ),
) -> None:
    """In CI: write config/ from the DEPLOYCTL_CONFIG secret, after checking its digest.

    Reads DEPLOYCTL_CONFIG and DEPLOYCTL_CONFIG_DIGEST from the environment, never
    from arguments, which would show in process listings. Under GitHub Actions it
    first registers every credential inside the bundle with ::add-mask:: — GitHub
    masks the secret's own value, not what is decoded from it.
    """
    if not env:
        # resolve_env would look in config/, which is exactly what is empty here.
        ui.error("--env is required: config/ is empty until this command fills it")
        raise typer.Exit(2)

    blob = os.environ.get(bundle.SECRET_NAME, "")
    expected = os.environ.get(bundle.DIGEST_NAME, "")
    if not blob:
        ui.error(f"{bundle.SECRET_NAME} is empty — not set on the GitHub environment '{env}' nor the "
                 f"repository, or the job does not pass it: deployctl ci sync-config --env {env}")
        raise typer.Exit(1)
    try:
        files = bundle.decode(blob, env)
    except bundle.BundleError as exc:
        ui.error(str(exc))
        raise typer.Exit(1) from None

    # Before anything else is printed. Outside Actions these lines would PRINT the
    # values instead of hiding them, so they are only ever emitted inside it.
    if os.environ.get("GITHUB_ACTIONS") == "true":
        for value in bundle.mask_values(env, files):
            print(bundle.mask_command(value))
        sys.stdout.flush()

    if not expected:
        ui.error(f"{bundle.DIGEST_NAME} is empty — set by `deployctl ci sync-config` beside the secret")
        raise typer.Exit(1)
    actual = bundle.digest(files)
    if actual != expected:
        ui.error(f"the config bundle does not match {bundle.DIGEST_NAME} ({actual[:19]}… ≠ {expected[:19]}…)")
        ui.hint(f"the two were set separately; re-run from the machine with the config: "
                f"deployctl ci sync-config --env {env} --force")
        raise typer.Exit(1)

    try:
        written = bundle.write(env, files, force=force)
    except bundle.BundleError as exc:
        ui.error(str(exc))
        raise typer.Exit(1) from None
    ui.ok(f"config for '{env}' written ({actual[:19]}…): {', '.join(written)}")


# ---- ci doctor -----------------------------------------------------------------------


def _check(items: list[dict], key: str, status: str, title: str, detail: str = "", fix: str = "",
           **extra: str) -> None:
    items.append({"id": key, "status": status, "title": title, "detail": detail, "fix": fix, **extra})


def doctor_items(cfg: Config, repo_level: bool = False) -> list[dict]:
    """Every piece CI/CD needs, checked: status ok | warn | todo | fail."""
    items: list[dict] = []
    env = cfg.env
    try:
        github.require()
        info = github.repo()
    except github.GitHubError as exc:
        _check(items, "github", "fail", "GitHub CLI", str(exc), "gh auth login")
        return items
    _check(items, "github", "ok", "GitHub", f"{info['name']} ({'private' if info['private'] else 'public'})")

    if cfg.raw["CI_SCOPE"]:
        _check(items, "scope", "ok", "Where secrets live", cfg.raw["CI_SCOPE"])
    else:
        _check(items, "scope", "todo", "Where secrets live", "not decided yet", f"deployctl ci connect --env {env}")
    scope = scope_env(cfg, repo_level)

    wf = workflows_dir()
    for name in MANAGED:
        path = wf / name
        if not path.is_file():
            _check(items, f"workflow:{name}", "todo", f".github/workflows/{name}", "missing",
                   f"deployctl ci init --env {env}")
            continue
        header = _MANAGED_HEADER.match(path.read_text())
        if header and header.group(1) != __version__:
            _check(items, f"workflow:{name}", "warn", f".github/workflows/{name}",
                   f"from deployctl {header.group(1)}, this is {__version__}", f"deployctl ci init --env {env} --force")
        elif not header:
            _check(items, f"workflow:{name}", "warn", f".github/workflows/{name}",
                   "hand-written, not generated", f"deployctl ci init --env {env} --force")
        else:
            _check(items, f"workflow:{name}", "ok", f".github/workflows/{name}", "current")
    ci_text = (wf / OWNED).read_text() if (wf / OWNED).is_file() else ""
    if "deploy.yml" in ci_text:
        _check(items, "workflow:ci", "ok", f".github/workflows/{OWNED}", "calls the deploy workflow")
    else:
        _check(items, "workflow:ci", "todo", f".github/workflows/{OWNED}",
               "missing" if not ci_text else "never calls deploy.yml", f"deployctl ci init --env {env}")

    try:
        names = github.secret_names(scope)
        values = github.variables(scope)
    except github.GitHubError as exc:
        _check(items, "secrets", "fail", f"Secrets on {_where(cfg, scope)}", str(exc),
               f"deployctl ci connect --env {env}")
        return items
    repo_values = values if scope is None else _safe_variables(None)

    if "DEPLOY_SSH_KEY" in names:
        _check(items, "ssh-key", "ok", "CI ssh key (DEPLOY_SSH_KEY)", "set")
    else:
        _check(items, "ssh-key", "todo", "CI ssh key (DEPLOY_SSH_KEY)", "not set", f"deployctl ci setup-key --env {env}")

    pinned = values.get("DEPLOY_KNOWN_HOSTS", "")
    wanted = list(cfg.hosts) + ([_jump_target(cfg.raw["SSH_JUMP_HOST"])[0]] if cfg.raw["SSH_JUMP_HOST"] else [])
    uncovered = [host for host in wanted if not _covers(pinned, host)]
    if not pinned:
        _check(items, "host-keys", "todo", "Pinned host keys", "not set", f"deployctl ci pin-hosts --env {env}")
    elif uncovered:
        _check(items, "host-keys", "todo", "Pinned host keys", f"missing for {', '.join(uncovered)}",
               f"deployctl ci pin-hosts --env {env}")
    else:
        _check(items, "host-keys", "ok", "Pinned host keys", f"every host ({len(wanted)})")

    digest = values.get(bundle.DIGEST_NAME)
    if bundle.SECRET_NAME not in names or not digest:
        _check(items, "config", "todo", "Deploy config in GitHub", "not uploaded", f"deployctl ci sync-config --env {env}")
    else:
        try:
            local = bundle.digest(bundle.collect(env))
        except bundle.BundleError as exc:
            _check(items, "config", "warn", "Deploy config in GitHub", str(exc))
        else:
            if local == digest:
                _check(items, "config", "ok", "Deploy config in GitHub", "matches this machine")
            else:
                _check(items, "config", "warn", "Deploy config in GitHub", "differs from this machine's config/",
                       f"deployctl ci sync-config --env {env}")

    tool_private = github.gh(["repo", "view", TOOL_REPO, "--json", "visibility", "--jq", ".visibility"]).stdout.strip()
    if tool_private and tool_private != "PUBLIC" and "DEPLOYCTL_INSTALL_TOKEN" not in names:
        _check(items, "install-token", "todo", "Installing deployctl in CI",
               f"{TOOL_REPO} is private and DEPLOYCTL_INSTALL_TOKEN is not set",
               "a fine-grained token, Contents: read on that repository → gh secret set DEPLOYCTL_INSTALL_TOKEN")
    else:
        _check(items, "install-token", "ok", "Installing deployctl in CI",
               "token set" if "DEPLOYCTL_INSTALL_TOKEN" in names else f"{TOOL_REPO} is public")

    auto = repo_values.get("AUTO_DEPLOY", "")
    _check(items, "auto-deploy", "ok", "Automatic deploys",
           f"on — every push to {cfg.raw['DEPLOY_BRANCH']} deploys" if auto == "true" else "off — deploy with `ci deploy`",
           value="on" if auto == "true" else "off")
    return items


def _safe_variables(scope: str | None) -> dict[str, str]:
    try:
        return github.variables(scope)
    except github.GitHubError:
        return {}


def _covers(known_hosts: str, host: str) -> bool:
    """Does a known_hosts text hold a key for host? Hashed entries are checked by ssh-keygen."""
    if not known_hosts:
        return False
    with tempfile.NamedTemporaryFile("w", suffix=".known_hosts", delete=False) as handle:
        handle.write(known_hosts + "\n")
        path = handle.name
    try:
        proc = subprocess.run(["ssh-keygen", "-F", host, "-f", path], capture_output=True, text=True)
        return proc.returncode == 0 and bool(proc.stdout.strip())
    finally:
        os.unlink(path)


_MARK = {"ok": "✓", "warn": "!", "todo": "·", "fail": "✗"}


@ci_app.command("doctor")
def doctor(
    env: str = env_option(),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable, for the control panel."),
    repo_level: bool = _repo_level_option,
) -> None:
    """Check everything continuous deployment needs, and say what to run for each gap.

    Exit 0 when nothing is missing, 1 otherwise.
    """
    cfg = load_config(env, require_valid=False)
    items = doctor_items(cfg, repo_level)
    if as_json:
        print(json.dumps({"env": cfg.env, "items": items}, indent=2))
    else:
        ui.header(f"CI doctor — {cfg.env}")
        for item in items:
            print(f"  {_MARK[item['status']]} {item['title']:<32} {item['detail']}")
            if item["fix"] and item["status"] != "ok":
                ui.hint(item["fix"])
    if any(item["status"] in ("todo", "fail") for item in items):
        raise typer.Exit(1)


# ---- ci deploy / runs / auto-deploy --------------------------------------------------


@ci_app.command("deploy")
def deploy(
    env: str = env_option(),
    tag: str = typer.Option(None, "--tag", "-t", help="Image tag. Default: the running one (to ship a config "
                            "change), or with --rollback the release before it."),
    rollback: bool = typer.Option(False, "--rollback", help="Roll back instead: never migrates."),
    allow_config_change: bool = typer.Option(
        False, "--allow-config-change", help="Ship config values that differ from what the hosts run."),
    watch: bool = typer.Option(True, "--watch/--no-watch", help="Follow the run until it finishes."),
) -> None:
    """Run the deploy workflow on GitHub — the everyday way to deploy by hand.

    Deploys through the same workflow merges use, with GitHub's copy of the config
    and the CI key, so every deploy lands in one history.
    """
    env_name = resolve_env(env)
    cfg = load_config(env_name)
    _github()
    if not tag:
        running = tags.running(cfg)
        if rollback:
            history = run(cfg, "deploy.sh", ["history"], check=False, capture=True).stdout
            tag = previous_release(parse_history(history, env_name), running) or ""
        else:
            tag = running
        if not tag:
            ui.error("no tag to deploy: pass --tag" + ("" if not rollback else " (no earlier release is recorded)"))
            raise typer.Exit(2)
    try:
        tags.check(tag)
    except tags.NoTag as exc:
        ui.error(str(exc))
        raise typer.Exit(2) from None

    action = "rollback" if rollback else "update"
    started = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(seconds=5)
    try:
        github.dispatch("deploy.yml", cfg.raw["DEPLOY_BRANCH"], {
            "environment": env_name, "tag": tag, "action": action,
            "allow_config_change": "true" if allow_config_change else "false",
        })
    except github.GitHubError as exc:
        ui.error(str(exc))
        ui.hint(f"is deploy.yml on {cfg.raw['DEPLOY_BRANCH']} and the default branch? deployctl ci doctor")
        raise typer.Exit(1) from None
    ui.ok(f"started: {action} {tag} → {env_name} (from {cfg.raw['DEPLOY_BRANCH']})")
    if not watch:
        return

    run_id = None
    for _ in range(20):  # the run appears a few seconds after the dispatch
        for item in github.runs("deploy.yml", limit=5, event="workflow_dispatch"):
            created = datetime.datetime.fromisoformat(item["createdAt"].replace("Z", "+00:00"))
            if created >= started:
                run_id = item["databaseId"]
                ui.info(item["url"])
                break
        if run_id:
            break
        time.sleep(3)
    if not run_id:
        ui.warn("started, but the run did not show up to follow — see: deployctl ci runs")
        return
    raise typer.Exit(github.watch(run_id))


def deploy_runs(cfg: Config, limit: int = 10) -> list[dict]:
    """Deploys through GitHub, newest first: manual ones, and those a push to the deploy branch ran."""
    out = []
    for item in github.runs("deploy.yml", limit=limit, event="workflow_dispatch"):
        title = item.get("displayTitle", "")
        parts = title.split()
        out.append({
            "at": item["createdAt"], "trigger": "manual",
            "action": parts[0] if parts else "update", "tag": parts[1] if len(parts) > 1 else "",
            "status": item.get("conclusion") or item.get("status", ""), "url": item["url"],
        })
    for item in github.runs(OWNED, limit=limit, branch=cfg.raw["DEPLOY_BRANCH"], event="push"):
        job = next((j for j in github.run_jobs(item["databaseId"])
                    if j.get("name", "").lower().startswith("deploy")), None)
        if job is None or job.get("conclusion") == "skipped":
            continue
        out.append({
            "at": item["createdAt"], "trigger": "merge", "action": "update", "tag": item["headSha"][:7],
            "status": job.get("conclusion") or job.get("status", ""), "url": item["url"],
        })
    return sorted(out, key=lambda r: r["at"], reverse=True)[:limit]


@ci_app.command("runs")
def runs(
    env: str = env_option(),
    limit: int = typer.Option(10, "--limit", "-n", help="How many."),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable, for the control panel."),
) -> None:
    """Recent deploys through GitHub — manual and on merge — with their outcome."""
    cfg = load_config(env, require_valid=False)
    _github()
    found = deploy_runs(cfg, limit)
    if as_json:
        print(json.dumps(found, indent=2))
        return
    if not found:
        ui.warn("no deploys through GitHub yet")
        return
    for item in found:
        print(f"  {item['at']}  {item['status'] or '…':<10} {item['action']:<9} {item['tag']:<10} "
              f"{item['trigger']:<7} {item['url']}")


@ci_app.command("auto-deploy")
def auto_deploy(
    state: str = typer.Argument(..., help="on or off"),
    env: str = env_option(),
) -> None:
    """Turn deploy-on-merge on or off (the repository variable AUTO_DEPLOY)."""
    if state not in ("on", "off"):
        ui.error("say on or off")
        raise typer.Exit(2)
    cfg = load_config(env, require_valid=False)
    _github()
    try:
        # Repository level whatever CI_SCOPE says: ci.yml reads it in a job's `if`,
        # before any environment is entered.
        github.set_variable("AUTO_DEPLOY", "true" if state == "on" else "false", None)
    except github.GitHubError as exc:
        ui.error(str(exc))
        raise typer.Exit(1) from None
    if state == "on":
        ui.ok(f"on — every push to {cfg.raw['DEPLOY_BRANCH']} that passes its checks deploys itself")
    else:
        ui.ok("off — deploy with: deployctl ci deploy")
