"""
Rendering templates into ``generated/``.

Jinja2 with ``StrictUndefined``: referencing a name that does not exist is a hard
error naming the template and line. That single setting replaces three separate
defences the shell implementation needed — a hand-maintained substitution table, a
"did any placeholder survive?" post-pass, and an allowlist of conditional flags to
stop a typo silently deleting a whole service block.

``generated/`` is laid out exactly as ``REMOTE_DIR`` will be on each target, so the
compose file's relative mounts (``../.env.<env>``, ``../nginx/…``) resolve the same
on the control machine and on a server.
"""

from __future__ import annotations

import hashlib
import os
import pathlib
import shutil

import jinja2

from . import paths, secrets
from .config import Config
from .envfile import assignment_key, parse_env_text, patch_env_file, quote_value, read_env_file, write_env_file

#: Files whose contents are secret and must not be world-readable. These are read
#: on the control machine and by the compose CLI running as ``SSH_USER`` — never
#: from inside a container, so 0600 costs nothing. The compose file is one of
#: them: a containerized Postgres takes its password from its `environment:`.
#: rsync carries the mode to the host, so this protects the server copy too.
_SECRET_ARTIFACTS = (".env.", "docker-compose.")

#: Secret-bearing files that are bind-mounted INTO a container, which is why they
#: cannot be 0600. rsync preserves the mode and the file arrives owned by
#: ``SSH_USER`` (uid 1000), while the official Redis image drops to uid 999 before
#: reading its config; an ``include`` it cannot open is fatal, so the container
#: never becomes healthy and every dependent service fails its dependency gate.
#: Confidentiality rests on REMOTE_DIR's ownership instead of the file mode.
_CONTAINER_READ_ARTIFACTS = ("redis-password.conf",)


def environment() -> jinja2.Environment:
    """The shared Jinja2 environment.

    ``trim_blocks``/``lstrip_blocks`` keep the YAML output clean: a ``{% if %}`` on
    its own line disappears entirely instead of leaving a stray blank line inside a
    compose service.
    """
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader([str(paths.TEMPLATES_DIR), str(paths.PROJECT_DIR)]),
        undefined=jinja2.StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
        autoescape=False,  # shell/YAML/nginx output, never HTML
    )
    # Compact JSON: a value like ["a", "b"] in an env file breaks anything that
    # word-splits the line (a shell sourcing it, for instance). Emit ["a","b"].
    env.policies["json.dumps_kwargs"] = {"separators": (",", ":"), "sort_keys": False}
    return env


_BANNER = """\
# Generated by deployctl — DO NOT EDIT.
# Source: templates/{template}
# Change config/{env}.env (or the template) and re-run: deployctl setup --env {env}
"""


def render_text(template_name: str, ctx: dict, *, banner: bool = True) -> str:
    """Render one template to a string."""
    env = environment()
    text = env.get_template(template_name).render(**ctx)
    if banner:
        comment = _BANNER.format(template=template_name, env=ctx["ENV"])
        return comment + text
    return text


def _write(path: pathlib.Path, content: str) -> pathlib.Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    secret = any(marker in path.name for marker in _SECRET_ARTIFACTS)
    write_env_file(path, content, secret=secret)
    # Set explicitly rather than leaving it to the umask: these files are rewritten
    # in place and write_text() keeps whatever mode they already had, so a
    # regenerate alone would not repair an artifact left at 0600 by an older build.
    if any(marker in path.name for marker in _CONTAINER_READ_ARTIFACTS):
        os.chmod(path, 0o644)
    return path


def _app_values(cfg: Config, project_keys: set[str], fresh: dict[str, str]) -> dict[str, str]:
    """The application keys an operator has set, from ``config/app.<env>.env`` — all of them.

    A key the template does not declare still ships: a field in project/fields.toml
    is enough to set one. Only the keys deployctl writes itself (the database,
    Redis, generated secrets — base.env.j2) cannot be replaced from here unless the
    template declares them too; ``checks.app_env_checks`` says when one is set.

    Those values used to be written into the rendered ``.env.<env>`` itself and
    carried from one render to the next — so the only copy of the app's API keys
    lived in generated/, the directory everything else treats as disposable, and
    an operator's value only survived when the template left the key blank: the
    panel's Save for a key with a template default (``MAIL_PROVIDER``,
    ``AUTH_GOOGLE_OAUTH_ENABLED``) was reverted by the next render. An existing
    install is adopted here, once, under the old rule — only keys that render
    blank — so nothing that was live changes on the way over.
    """
    path = paths.app_values_file(cfg.env)
    stored = read_env_file(path)
    legacy = read_env_file(paths.env_artifact(cfg.env))
    adopt = {
        key: value
        for key, value in legacy.items()
        if key in project_keys and value and not fresh.get(key) and key not in stored
    }
    if adopt:
        patch_env_file(path, adopt)
        stored.update(adopt)
    return {key: value for key, value in stored.items() if value and (key in project_keys or key not in fresh)}


def _project_block(ctx: dict) -> str:
    """``project/app.env.template`` rendered for one environment; empty without one."""
    if not paths.PROJECT_APP_ENV_TEMPLATE.is_file():
        return ""
    return environment().get_template(paths.PROJECT_APP_ENV_TEMPLATE.name).render(**ctx)


def app_env_layers(cfg: Config) -> tuple[dict[str, str], dict[str, str]]:
    """What ``.env.<env>`` is built from before the operator's own values: deployctl's
    block (``base.env.j2``) and the project's template, each rendered and parsed.

    Reads only — unlike a render, nothing is written, adopted or minted. A secret
    setup has not minted yet renders as a stand-in: the keys are what matter here.
    """
    unminted = {key: "not-minted-yet" for key in secrets.pinned(cfg) if not cfg.raw.get(key)}
    ctx = cfg.ctx(**unminted)
    return parse_env_text(render_text("env/base.env.j2", ctx)), parse_env_text(_project_block(ctx))


def _render_app_env(cfg: Config) -> str:
    """Build ``.env.<env>``: the tool-owned base plus the project-owned block.

    Project keys an operator set — in the control panel, or in
    ``config/app.<env>.env`` directly — replace whatever the template renders for
    them, blank or default. Without this, adding one API key and regenerating
    would silently blank every other one.
    """
    ctx = cfg.ctx()
    project_block = _project_block(ctx)
    parts = [render_text("env/base.env.j2", ctx)]

    if paths.PROJECT_APP_ENV_TEMPLATE.is_file():
        parts.append("\n" + project_block)

    rendered = "\n".join(parts)

    project_keys = set(parse_env_text(project_block))
    fresh = parse_env_text(rendered)
    preserved = {
        key: value
        for key, value in _app_values(cfg, project_keys, fresh).items()
        if value != fresh.get(key)
    }
    if not preserved:
        return rendered

    # Substituted onto the key's own line, not appended in a block at the end.
    # Appending leaves the file with two assignments for every preserved key —
    # `MAILGUN_API_KEY=` near the top and the real one forty lines below — which
    # reads as a blank value to anybody opening the file, and is only correct at
    # all because every consumer happens to let the last assignment win. The
    # comment the template already carries above each key stays with its value.
    remaining = dict(preserved)
    out: list[str] = []
    for line in rendered.splitlines():
        key = assignment_key(line)
        if key in remaining:
            out.append(f"{key}={quote_value(remaining.pop(key))}")
        else:
            out.append(line)

    # Keys the template does not declare: set in the panel or in the file directly.
    if remaining:
        out += [
            "",
            f"# ---- set in config/app.{cfg.env}.env, not declared in project/app.env.template ----",
            *(f"{k}={quote_value(v)}" for k, v in sorted(remaining.items())),
        ]
    return "\n".join(out) + "\n"


def render_all(cfg: Config) -> list[pathlib.Path]:
    """Render every artifact for one environment. Returns the paths written."""
    written: list[pathlib.Path] = []
    ctx = cfg.ctx()

    # 1. Application environment file (role-independent: identical on every host).
    written.append(_write(paths.env_artifact(cfg.env), _render_app_env(cfg)))

    # 2. nginx (role-independent).
    nginx = paths.nginx_dir(cfg.env)
    written.append(_write(nginx / "nginx.conf", render_text("nginx/nginx.conf.j2", ctx)))
    written.append(_write(nginx / "site.conf", render_text("nginx/site.conf.j2", ctx)))

    # The /docs basic-auth file is operator-managed server-side state. Create an
    # empty placeholder so the bind mount and nginx start cleanly on a fresh host;
    # an empty file means /docs returns 403, i.e. it fails closed.
    auth = nginx / "auth" / ".htpasswd"
    if not auth.exists():
        auth.parent.mkdir(parents=True, exist_ok=True)
        auth.touch()

    if cfg.derived["WITH_EXTRA_NGINX"]:
        extra = nginx / "extra" / "project.conf"
        extra.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(paths.PROJECT_NGINX_EXTRA, extra)
        written.append(extra)
    else:
        # nginx's include glob needs the directory to exist even when empty.
        (nginx / "extra").mkdir(parents=True, exist_ok=True)

    # 3. Redis config — only when Redis runs as a container here.
    redis_config_hash = ""
    if cfg.derived["WITH_REDIS"]:
        redis = paths.redis_dir(cfg.env)
        redis_conf = render_text("redis/redis.conf.j2", ctx)
        # requirepass lives in its own file that redis.conf includes, so the
        # password never appears in `ps` output.
        redis_password = f"# Generated by deployctl — DO NOT COMMIT.\nrequirepass {cfg.raw['REDIS_PASSWORD']}\n"
        written.append(_write(redis / "redis.conf", redis_conf))
        written.append(_write(redis / "redis-password.conf", redis_password))
        # Redis reads its config once, at start, from single-file bind mounts that
        # rsync replaces with new inodes — and compose sees an unchanged service
        # definition, so `up -d` leaves the old process running on the old config
        # forever. This hash, as a label on the service, is what makes a changed
        # config (or a rotated password) recreate the container.
        redis_config_hash = hashlib.sha256((redis_conf + redis_password).encode()).hexdigest()[:16]

    # 4. One compose file per role. Beat and migrations belong to the primary; a
    #    second Beat would double-fire every scheduled job.
    for role in cfg.roles:
        content = render_text(
            "docker/compose.yml.j2",
            cfg.ctx(SERVER_ROLE=role, IS_PRIMARY=(role == "primary"), REDIS_CONFIG_HASH=redis_config_hash),
        )
        written.append(_write(paths.compose_artifact(cfg.env, role), content))

    # 5. Extra services the project supplies, copied so it ships with the artifacts
    #    and can be referenced as a second -f on every compose invocation.
    if cfg.derived["WITH_EXTRA_COMPOSE"]:
        target = paths.compose_extra_artifact(cfg.env)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(paths.PROJECT_COMPOSE_EXTRA, target)
        written.append(target)

    return written


def clean(env: str) -> list[pathlib.Path]:
    """Remove the rendered artifacts for one environment (``setup --force``).

    Two files are deliberately left alone, for the same reason: they carry state
    nothing else can reconstruct.

    ``nginx/auth/.htpasswd``  operator-managed, never generated at all.

    ``.env.<env>``            on an install from before ``config/app.<env>.env``
                              existed, the only record of the project-owned
                              values — API keys, the mail provider's credentials.
                              :func:`_app_values` adopts them into config/ on the
                              next render; deleting the file first would adopt
                              nothing and blank every one of them.
                              :func:`render_all` rewrites the file in full, so
                              keeping it cannot leave anything stale.
    """
    removed: list[pathlib.Path] = []
    root = paths.env_root(env)
    targets = [paths.compose_extra_artifact(env)]
    targets += list(root.glob(f"*/docker-compose.{env}.yml"))
    targets += list(root.glob("nginx/*.conf"))
    targets += list(root.glob("nginx/extra/*.conf"))
    targets += list(root.glob("redis/*.conf"))
    for path in targets:
        if path.exists():
            path.unlink()
            removed.append(path)
    return removed


def stat_mode(path: pathlib.Path) -> str:
    """Octal permissions of a path, for validation output."""
    return oct(os.stat(path).st_mode & 0o777)[2:]


def world_readable(path: pathlib.Path) -> bool:
    """Whether any uid can read the file.

    Required of anything bind-mounted into a container: the process inside runs
    under an image-chosen uid that has no relationship to the file's owner.
    """
    return bool(os.stat(path).st_mode & 0o004)
